### PR TITLE
First docker setup configs

### PR DESCRIPTION
**Pull request by btamayo**
added Dockerfile, docker-compose file, removed babel-node-debug from package.json

### CODE REVIEW

**Comment by krainboltgreene** [comment]
@btamayo I think there was a build cache issue, because I was seemingly able to npm install just fine?

The last bit is weird, but I ran the command and it was fine.

```
$ docker-compose run api npm install

> bufferutil@1.2.1 install /usr/src/application/node_modules/bufferutil
> node-gyp rebuild

make: Entering directory '/usr/src/application/node_modules/bufferutil/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
./Release/.deps/Release/obj.target/bufferutil/src/bufferutil.o.d.raw { dev: 31,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 50,
  rdev: 0,
  blksize: 4096,
  ino: 6096,
  size: 1211,
  blocks: 8,
  atime: Sun Apr 10 2016 01:05:27 GMT+0000 (UTC),
  mtime: Sun Apr 10 2016 01:05:27 GMT+0000 (UTC),
  ctime: Sun Apr 10 2016 01:05:27 GMT+0000 (UTC),
  birthtime: Sun Apr 10 2016 01:05:27 GMT+0000 (UTC) }
  SOLINK_MODULE(target) Release/obj.target/bufferutil.node
  COPY Release/bufferutil.node
make: Leaving directory '/usr/src/application/node_modules/bufferutil/build'

> dtrace-provider@0.6.0 install /usr/src/application/node_modules/dtrace-provider
> node scripts/install.js


> fsevents@1.0.11 install /usr/src/application/node_modules/fsevents
> node-pre-gyp install --fallback-to-build

make: Entering directory '/usr/src/application/node_modules/fsevents/build'
  SOLINK_MODULE(target) Release/obj.target/.node
  COPY Release/.node
make: Leaving directory '/usr/src/application/node_modules/fsevents/build'
npm WARN prefer global node-inspector@0.12.7 should be installed with -g

> spawn-sync@1.0.15 postinstall /usr/src/application/node_modules/spawn-sync
> node postinstall


> utf-8-validate@1.2.1 install /usr/src/application/node_modules/utf-8-validate
> node-gyp rebuild

make: Entering directory '/usr/src/application/node_modules/utf-8-validate/build'
  CXX(target) Release/obj.target/validation/src/validation.o
./Release/.deps/Release/obj.target/validation/src/validation.o.d.raw { dev: 31,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 50,
  rdev: 0,
  blksize: 4096,
  ino: 6247,
  size: 1211,
  blocks: 8,
  atime: Sun Apr 10 2016 01:05:43 GMT+0000 (UTC),
  mtime: Sun Apr 10 2016 01:05:43 GMT+0000 (UTC),
  ctime: Sun Apr 10 2016 01:05:44 GMT+0000 (UTC),
  birthtime: Sun Apr 10 2016 01:05:44 GMT+0000 (UTC) }
  SOLINK_MODULE(target) Release/obj.target/validation.node
  COPY Release/validation.node
make: Leaving directory '/usr/src/application/node_modules/utf-8-validate/build'

> v8-debug@0.7.1 preinstall /usr/src/application/node_modules/v8-debug
> node -e 'process.exit(0)'


> v8-debug@0.7.1 install /usr/src/application/node_modules/v8-debug
> node-pre-gyp install --fallback-to-build

[v8-debug] Success: "/usr/src/application/node_modules/v8-debug/build/debug/v0.7.1/node-v46-linux-x64/debug.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> v8-profiler@5.6.0 preinstall /usr/src/application/node_modules/v8-profiler
> node -e 'process.exit(0)'


> v8-profiler@5.6.0 install /usr/src/application/node_modules/v8-profiler
> node-pre-gyp install --fallback-to-build

[v8-profiler] Success: "/usr/src/application/node_modules/v8-profiler/build/profiler/v5.6.0/node-v46-linux-x64/profiler.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile
npm WARN cannot run in wd api@1.0.0 npm run build (wd=/usr/src/application)
```

**Comment by krainboltgreene** [comment]
So close!

```
api_1      | [nodemon] starting `node ./tmp/server/index.js`
api_1      | Throng booting ("1" workers)
api_1      | Knex:Error Pool2 - Error: connect ECONNREFUSED 127.0.0.1:5432
api_1      | Knex:Error Pool2 - Error: connect ECONNREFUSED 127.0.0.1:5432
api_1      | [nodemon] clean exit - waiting for changes before restart
```

**Comment by krainboltgreene** [comment]
Ugh, no now I get why it installed fine. Volume just coppeid over my `node_modules` directory. Poop.

**Comment by krainboltgreene** [comment]
https://github.com/mhart/alpine-node :|

**Comment by btamayo** [comment]
LOL

**Comment by krainboltgreene** [comment]
So there's an [alpine-postgres](https://github.com/kiasaki/docker-alpine-postgres), heavily considering it but it's also stuck on alpine 3.2, not sure if this is a problem.

**Comment by krainboltgreene** [comment]
Amusingly while the dockerfile specifies 9.4, the way `apk` works it'll actually go up to 9.5.

**Comment by krainboltgreene** [comment]
Okay, I discovered the second time why I didn't want to `VOLUME .:/thing`, because it's two ways. Going to try and add my rsync method again.

**Comment by krainboltgreene** [comment]
```
➜  api git:(docker-setup) ✗ docker-compose run api npm run lint

> api@1.0.0 lint /usr/src/api
> npm-run-all --parallel lint:server lint:remote


> api@1.0.0 lint:remote /usr/src/api
> eslint './remote/'


> api@1.0.0 lint:server /usr/src/api
> eslint './server/'
```

💃 💃 💃 💃

**Comment by btamayo** [comment]
🎊 🎉🎊💫

(GH reactions need to step it up)

**Comment by krainboltgreene** [comment]
Okay, so setup looks like this:

```
$ git clone lacqueristas/api
install docker-toolbox
install docker-rync
dump .env
$ docker-compose build
$ docker-rsync -watch=false -dst="/usr/src/" default
$ docker-compose run api npm install
$ docker-compose run api npm run data:migrate
$ docker-compose run api npm run data:seed
$ docker-compose up
```

**Comment by krainboltgreene** [comment]
Got it to actually run migrations locally, that was fun.

Here's the env file:

```
NODE_ENV=development
PORT=8081
WEB_CONCURRENCY=1
DATABASE_URL=postgres://lacqueristas:password@database:5432/api
DATABASE_POOL_MINIMUM=1
DATABASE_POOL_MAXIMUM=10
KEENIO_API_PUBLIC=x
KEENIO_API_PRIVATE=x
PUSHER_API_ID=x
PUSHER_API_PUBLIC=x
PUSHER_API_PRIVATE=x
CORS_AC_ALLOW_ORIGIN=http://localhost:8080
CORS_AC_ALLOW_HEADERS=x
CORS_AC_EXPOSE_HEADERS=x
CORS_AC_MAX_AGE=10
LETSENCRYPT_PUBLIC=x
LETSENCRYPT_PRIVATE=x
POSTGRES_USER=lacqueristas
POSTGRES_DB=api
POSTGRES_PASSWORD=password
```

**Comment by krainboltgreene** [comment]
Sadly I think it's fair to say local development via docker and node.js, with modern tooling, isn't really usable.

What this means is I think we can just remove rsync from the process, switch back to volumes, and then just not use docker locally.

Next step: Getting deis setup.

**Comment by krainboltgreene** [comment]
```
docker-compose up
Recreating api_api_1
api_database_1 is up-to-date
Attaching to api_api_1, api_database_1
database_1 | LOG:  database system was shut down at 2016-04-11 01:14:39 UTC
database_1 | LOG:  MultiXact member wraparound protections are now enabled
database_1 | LOG:  database system is ready to accept connections
database_1 | LOG:  autovacuum launcher started
database_1 | LOG:  received smart shutdown request
database_1 | LOG:  autovacuum launcher shutting down
database_1 | LOG:  shutting down
database_1 | LOG:  database system is shut down
database_1 | LOG:  database system was shut down at 2016-04-11 01:14:59 UTC
database_1 | LOG:  MultiXact member wraparound protections are now enabled
database_1 | LOG:  database system is ready to accept connections
database_1 | LOG:  autovacuum launcher started
database_1 | LOG:  received smart shutdown request
database_1 | LOG:  autovacuum launcher shutting down
database_1 | LOG:  shutting down
database_1 | LOG:  database system is shut down
database_1 | LOG:  database system was shut down at 2016-04-11 01:15:52 UTC
database_1 | LOG:  MultiXact member wraparound protections are now enabled
database_1 | LOG:  database system is ready to accept connections
database_1 | LOG:  autovacuum launcher started
api_1      |
api_1      | > api@1.0.0 server /usr/src/api
api_1      | > npm run server:`echo $NODE_ENV`
api_1      |
api_1      |
api_1      | > api@1.0.0 server:production /usr/src/api
api_1      | > node './tmp/server/index.js'
api_1      |
api_1      | Throng booting (1 workers)
api_1      | Throng booting (1 workers)
api_1      | Worker 1 booting...
api_1      | Applying funnel...
api_1      | Listening to 8081!
```

**Comment by krainboltgreene** [comment]
```
$ git clone lacqueristas/api
install docker-toolbox
dump .env
$ docker-compose build
$ docker-compose run api npm run data:migrate
$ docker-compose run api npm run data:seed
$ docker-compose up
```

**Comment by btamayo** [comment]
Hm, we should add this to the README as some point

**Comment by krainboltgreene** [comment]
Added new details and docker setup notes.

**Comment by krainboltgreene** [comment]
Honestly I think this puts this PR in accept range.

**Comment by btamayo** [comment]
Yup, agreed.

**Comment by krainboltgreene** [comment]
🎈

**Pull request merged**
